### ISSUE TITLE
支持API命名空间

### ISSUE THREAD

**Issue by xiaohegg** [751496032/DSBridge-HarmonyOS#1]
暂不支持API命名空间，后续会根据需求决定是否支持?
这个什么时候能支持，我们有这个需求，跟安卓一样的模式

**Comment by 751496032** [comment]
安排年后上

**Comment by 751496032** [comment]
> 暂不支持API命名空间，后续会根据需求决定是否支持? 这个什么时候能支持，我们有这个需求，跟安卓一样的模式

已支持
