### ISSUE TITLE
最新的1.3.0不支持api9吗？

### ISSUE THREAD

**Issue by Panway** [751496032/DSBridge-HarmonyOS#10]
错误如下：
> hvigor ERROR: Failed :entry:default@MergeProfile... 
> hvigor ERROR: The compatibleSdkVersion 9 cannot be smaller than version 11 declared in library [:library] 
          as the library might be using APIS not available in 9

看起来像是只支持11以上的项目了

**Comment by 751496032** [comment]
> 错误如下：
> 
> > hvigor ERROR: Failed :entry:default@MergeProfile...
> > hvigor ERROR: The compatibleSdkVersion 9 cannot be smaller than version 11 declared in library [:library]
> > as the library might be using APIS not available in 9
> 
> 看起来像是只支持11以上的项目了

可以拉取dev-api9分支

**Comment by Panway** [comment]
感谢回复，经过测试可以下载`dev-api9`分支的[library.har](https://raw.githubusercontent.com/751496032/DSBridge-HarmonyOS/dev-api9/libs/library.har)到根目录，然后通过命令`ohpm install ./library.har` 安装
