### ISSUE TITLE
异步回调缺少对对象的支持

### ISSUE THREAD

**Issue by tianchong89** [751496032/DSBridge-HarmonyOS#11]
this.cHandler.complete(Object) //事变
export type Args = number | string | boolean  
缺少Object支持，希望 改成export type Args = number | string | boolean |Object 对返回对象也进行支持
这里也改
export interface CallResult {
  code: number,
  data?: string | boolean | number| Object,
  errMsg?: string,
  async?: boolean,
}
目前我自己改了没问题。我的问题解决

**Comment by 751496032** [comment]
> ```
>     this.cHandler.complete(Object) //事变
> ```
> 
> export type Args = number | string | boolean 缺少Object支持，希望 改成export type Args = number | string | boolean |Object 对返回对象也进行支持 这里也改 export interface CallResult { code: number, data?: string | boolean | number| Object, errMsg?: string, async?: boolean, } 目前我自己改了没问题。我的问题解决

ok , 也可以将对象转成json字符串，让h5去解析；不过为了兼容android 、ios端确实要支持对象

**Comment by 751496032** [comment]
> ```
>     this.cHandler.complete(Object) //事变
> ```
> 
> export type Args = number | string | boolean 缺少Object支持，希望 改成export type Args = number | string | boolean |Object 对返回对象也进行支持 这里也改 export interface CallResult { code: number, data?: string | boolean | number| Object, errMsg?: string, async?: boolean, } 目前我自己改了没问题。我的问题解决

也可以将对象转成json字符串，让h5去解析；不过为了兼容android 、ios端确实要支持对象 ；下一个版本会优化，谢谢反馈！
