### ISSUE TITLE
原生调用call方法，没有拿到前端返回的数据

### ISSUE THREAD

**Issue by luluaidota** [751496032/DSBridge-HarmonyOS#14]
原生调用call方法，没有拿到前端返回的数据

**Comment by 751496032** [comment]
> 原生调用call方法，没有拿到前端返回的数据

代码可以贴下不

**Comment by luluaidota** [comment]
export struct Browser {
  controller: web_webview.WebviewController = new web_webview.WebviewController();
  private controllerProxy: WebViewControllerProxy = new WebViewControllerProxy(this.controller)
  @State cacheMode: CacheMode = CacheMode.None
  @State url: string = ''
  @State title: string = ''
  @State loading: boolean = false
  @State error: boolean = false
  private params: BrowserParams | null = null

  aboutToAppear(): void {
    this.params = router.getParams() as BrowserParams
    this.url = this.params.url

    //配置web开启调试模式
    web_webview.WebviewController.setWebDebuggingAccess(true)
    this.setCookie()
    //注入jsBridge
    this.controllerProxy.addJavascriptObject(new JsBridge())
  }

  aboutToDisappear(): void {
    this.controllerProxy.destroy()
  }

  build() {
    Column() {
      BrowserNavHeader({
        title: this.title,
        onBack: () => {
          this.handleBack()
        },
        onClose: () => {
          router.back()
        },
        onShare: () => {
          this.shareAction()
        }
      })
      Stack() {
        Web({ src: this.url, controller: this.controller })
          .width('100%')
          .height('100%')
          .onTitleReceive((event) => {
            if (event?.title) {
              this.title = event.title
            }
          })
          .onControllerAttached(() => {
            this.controller.loadUrl(this.url)
          })
          .onPageBegin((event) => {
            this.loading = true
            this.setUserAgent()
          })
          .onPageEnd((event) => {
            this.loading = false
          })
          .onErrorReceive((event) => {
            if (event?.request.isMainFrame()) {
              this.error = true
            }
          })
          .fileAccess(true)
          .domStorageAccess(true)
          .onlineImageAccess(true)
          .javaScriptProxy(this.controllerProxy.javaScriptProxy)
          .javaScriptAccess(true)
          .cacheMode(this.cacheMode)

        // status layout
        if (this.loading || this.error) {
          StatusLayout({
            loading: this.loading,
            error: this.error,
            onReload: () => {
              this.error = false
              this.controller.refresh()
            }
          })
        }
      }
    }
    .width('100%')
    .height('100%')
  }

  handleBack() {
    let entries = this.controller.getBackForwardEntries()
    // 判断是否能goBack
    if (entries.currentIndex > 0) {
      this.controller.backward()
    } else {
      router.back()
    }
  }

  onBackPress(): boolean | void {
    // 自己处理返回事件
    this.handleBack()
    return true
  }

  async shareAction() {
    toast('点击分享')

    let haveMethod:Boolean = await this.controllerProxy.hasJavascriptMethod('web_share')
    if (haveMethod) {
      try {
        this.controllerProxy.callJs('web_share',null,(value:string) => {
          console.log(value)
        })
      } catch (error) {
        console.error('Failed to call JavaScript function:', error);
      }
    }
  }

}

点击分享按钮，需要能收到web端返回的数据，但是目前calljs方法没有回调

**Comment by 751496032** [comment]
> export struct Browser { controller: web_webview.WebviewController = new web_webview.WebviewController(); private controllerProxy: WebViewControllerProxy = new WebViewControllerProxy(this.controller) @State cacheMode: CacheMode = CacheMode.None @State url: string = '' @State title: string = '' @State loading: boolean = false @State error: boolean = false private params: BrowserParams | null = null
> 
> aboutToAppear(): void { this.params = router.getParams() as BrowserParams this.url = this.params.url
> 
> ```
> //配置web开启调试模式
> web_webview.WebviewController.setWebDebuggingAccess(true)
> this.setCookie()
> //注入jsBridge
> this.controllerProxy.addJavascriptObject(new JsBridge())
> ```
> 
> }
> 
> aboutToDisappear(): void { this.controllerProxy.destroy() }
> 
> build() { Column() { BrowserNavHeader({ title: this.title, onBack: () => { this.handleBack() }, onClose: () => { router.back() }, onShare: () => { this.shareAction() } }) Stack() { Web({ src: this.url, controller: this.controller }) .width('100%') .height('100%') .onTitleReceive((event) => { if (event?.title) { this.title = event.title } }) .onControllerAttached(() => { this.controller.loadUrl(this.url) }) .onPageBegin((event) => { this.loading = true this.setUserAgent() }) .onPageEnd((event) => { this.loading = false }) .onErrorReceive((event) => { if (event?.request.isMainFrame()) { this.error = true } }) .fileAccess(true) .domStorageAccess(true) .onlineImageAccess(true) .javaScriptProxy(this.controllerProxy.javaScriptProxy) .javaScriptAccess(true) .cacheMode(this.cacheMode)
> 
> ```
>     // status layout
>     if (this.loading || this.error) {
>       StatusLayout({
>         loading: this.loading,
>         error: this.error,
>         onReload: () => {
>           this.error = false
>           this.controller.refresh()
>         }
>       })
>     }
>   }
> }
> .width('100%')
> .height('100%')
> ```
> 
> }
> 
> handleBack() { let entries = this.controller.getBackForwardEntries() // 判断是否能goBack if (entries.currentIndex > 0) { this.controller.backward() } else { router.back() } }
> 
> onBackPress(): boolean | void { // 自己处理返回事件 this.handleBack() return true }
> 
> async shareAction() { toast('点击分享')
> 
> ```
> let haveMethod:Boolean = await this.controllerProxy.hasJavascriptMethod('web_share')
> if (haveMethod) {
>   try {
>     this.controllerProxy.callJs('web_share',null,(value:string) => {
>       console.log(value)
>     })
>   } catch (error) {
>     console.error('Failed to call JavaScript function:', error);
>   }
> }
> ```
> 
> }
> 
> }
> 
> 点击分享按钮，需要能收到web端返回的数据，但是目前calljs方法没有回调

   this.controllerProxy.callJs('web_share',null,(value:string)  把null 改成 []试试，无参或者使用callJsMethodWithoutParam

**Comment by luluaidota** [comment]
解决了，大佬yyds
