### ISSUE TITLE
目前工程用的dsbridge.js-2.0，框架好像不适配2.0的js，无法调用js函数

### ISSUE THREAD

**Issue by ZhouJze** [751496032/DSBridge-HarmonyOS#20]
提示Script error，根据安卓DSBridge工程readme判断。不确定是否正确。js调用原生正常。

**Comment by 751496032** [comment]
> 提示Script error，根据安卓DSBridge工程readme判断。不确定是否正确。js调用原生正常。

贴下示例代码看看

**Comment by 751496032** [comment]
> 提示Script error，根据安卓DSBridge工程readme判断。不确定是否正确。js调用原生正常。

目前没有适配2.0的js脚本
