### ISSUE TITLE
现在由js传到原生的数据包裹了一层.data，没有data包裹的数据将获取不到，后续能否支持获取全部js传来的数据，或者由自己定义过滤

### ISSUE THREAD

**Issue by ZhouJze** [751496032/DSBridge-HarmonyOS#21]
let jsParam: Parameter = this.safeParse(params)
      // todo 待优化
      async = (jsParam._dscbstub != null && jsParam._dscbstub !== undefined) || async
      LogUtils.d("async: " + async + " --- " + methodName)
      let data: string = (this.isObject(**jsParam.data**) ? JSON.stringify(**jsParam.data**) : **jsParam.data**) as string

**Comment by 751496032** [comment]
> ```
>   let jsParam: Parameter = this.safeParse(params)
>   // todo 待优化
>   async = (jsParam._dscbstub != null && jsParam._dscbstub !== undefined) || async
>   LogUtils.d("async: " + async + " --- " + methodName)
>   let data: string = (this.isObject(**jsParam.data**) ? JSON.stringify(**jsParam.data**) : **jsParam.data**) as string
> ```

行 这几天我看看

**Comment by ZhouJze** [comment]
> > ```
> >   let jsParam: Parameter = this.safeParse(params)
> >   // todo 待优化
> >   async = (jsParam._dscbstub != null && jsParam._dscbstub !== undefined) || async
> >   LogUtils.d("async: " + async + " --- " + methodName)
> >   let data: string = (this.isObject(**jsParam.data**) ? JSON.stringify(**jsParam.data**) : **jsParam.data**) as string
> > ```
> 
> 行这几天我看看，你们是用的是2.0的js?

对的，目前安卓两个项目和ios端用的全是2.0的DSBridge，所以js要升级3.0有点难。

**Comment by ZhouJze** [comment]
> > ```
> >   let jsParam: Parameter = this.safeParse(params)
> >   // todo 待优化
> >   async = (jsParam._dscbstub != null && jsParam._dscbstub !== undefined) || async
> >   LogUtils.d("async: " + async + " --- " + methodName)
> >   let data: string = (this.isObject(**jsParam.data**) ? JSON.stringify(**jsParam.data**) : **jsParam.data**) as string
> > ```
> 
> 行这几天我看看，你们是用的是2.0的js?

对的，因为之前的项目安卓和ios端用的都是DSBridge2.0。麻烦您啦。

**Comment by 751496032** [comment]
> > > ```
> > >   let jsParam: Parameter = this.safeParse(params)
> > >   // todo 待优化
> > >   async = (jsParam._dscbstub != null && jsParam._dscbstub !== undefined) || async
> > >   LogUtils.d("async: " + async + " --- " + methodName)
> > >   let data: string = (this.isObject(**jsParam.data**) ? JSON.stringify(**jsParam.data**) : **jsParam.data**) as string
> > > ```
> > 
> > 
> > 行这几天我看看，你们是用的是2.0的js?
> 
> 对的，因为之前的项目安卓和ios端用的都是DSBridge2.0。麻烦您啦。

已支持ds2.0了，可以拉下ds2分支测试下，没问题再发布

```
  aboutToAppear() {
    // 如果是使用DSBridge2.0 ，调用supportDS2方法
    this.controller.supportDS2(true)
    // 以下两种注册方式都可以，任选其一
    this.controller.addJavascriptObject(this)
    // this.controller.addJavascriptObject(new JsBridge2())
    // DS2.0脚本不支持API命令空间
    // this.controller.addJavascriptObject(new JsBridge2(),'js2')
    // 开启调试模式
    webview.WebviewController.setWebDebuggingAccess(true);
  }

```

**Comment by 751496032** [comment]
> > > ```
> > >   let jsParam: Parameter = this.safeParse(params)
> > >   // todo 待优化
> > >   async = (jsParam._dscbstub != null && jsParam._dscbstub !== undefined) || async
> > >   LogUtils.d("async: " + async + " --- " + methodName)
> > >   let data: string = (this.isObject(**jsParam.data**) ? JSON.stringify(**jsParam.data**) : **jsParam.data**) as string
> > > ```
> > 
> > 
> > 行这几天我看看，你们是用的是2.0的js?
> 
> 对的，因为之前的项目安卓和ios端用的都是DSBridge2.0。麻烦您啦。

已适配ds2 ，可以拉下分支ds2 试试，没什么问题就发一个版

```
  aboutToAppear() {
    // 如果是使用DSBridge2.0 ，调用supportDS2方法
    this.controller.supportDS2(true)
    // 以下两种注册方式都可以，任选其一
    this.controller.addJavascriptObject(this)
    // this.controller.addJavascriptObject(new JsBridge2())
    // DS2.0脚本不支持API命令空间
    // this.controller.addJavascriptObject(new JsBridge2(),'js2')
    // 开启调试模式
    webview.WebviewController.setWebDebuggingAccess(true);
  }
```
