### ISSUE TITLE
如果原项目三端都没有使用dsBridge的库，可以只在鸿蒙使用dsBridge这个库吗？

### ISSUE THREAD

**Issue by super-zhao** [751496032/DSBridge-HarmonyOS#23]
原项目js使用类似window.coreyl.pushFun(JSON.stringify(obj)));  
android端使用
<img width="644" alt="image" src="https://github.com/user-attachments/assets/8ada3a0b-a7e2-45b5-b2cf-6e7efbfa0719">
来接收方法名及参数

这种情况使用DSBridge怎么处理呢？

**Comment by 751496032** [comment]
> 原项目js使用类似window.coreyl.pushFun(JSON.stringify(obj))); android端使用 <img alt="image" width="644" src="https://private-user-images.githubusercontent.com/13294882/348705877-8ada3a0b-a7e2-45b5-b2cf-6e7efbfa0719.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTczNjksIm5iZiI6MTcyMTA1NzA2OSwicGF0aCI6Ii8xMzI5NDg4Mi8zNDg3MDU4NzctOGFkYTNhMGItYTdlMi00NWI1LWIyY2YtNmU3ZWZiZmEwNzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE1MjQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ZDA5ZmUxZWY2MmQ2Nzc4M2YwYTExMGRiNTQyMDc2YzgyMzZlM2U1ZjJhZDk1ZjQ4NmZmMTJkZTFkYTFlMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TGTPDMGbcW30Jm9itGCyegQ3jsbljsfEi7uGCzZEJoU"> 来接收方法名及参数
> 
> 这种情况使用DSBridge怎么处理呢？

如果原前端不是使用DSBridge脚本的话，在鸿蒙上直接用是不兼容的，因为注入的JS对象和脚本逻辑是不一样的
