### ISSUE TITLE
鸿蒙next的不支持

### ISSUE THREAD

**Issue by name718** [751496032/DSBridge-HarmonyOS#4]

**Comment by 751496032** [comment]
> _No description provided._

正在适配中

**Comment by yinjianjun1** [comment]
> > _No description provided._
> 
> 正在适配中

预计版本在几月会正式发布？

**Comment by 751496032** [comment]
> > > _No description provided._
> > 
> > 
> > 正在适配中
> 
> 预计版本在几月会正式发布？

已经适配了
