### ISSUE TITLE
使用未定义的Native方法，直接退出应用程序

### ISSUE THREAD

**Issue by langxiaojin** [751496032/DSBridge-HarmonyOS#5]
当在web端调用Native未定义的方法时，由于使用throw new Error()，导致鸿蒙应用直接退出。
建议改成相同的体验，使用Prompt.showToast方法支持报错信息提示。

<img width="1038" alt="image" src="https://github.com/751496032/DSBridge-HarmonyOS/assets/18252626/533b9a4f-7025-4da9-8af9-62c39af83520">

**Comment by 751496032** [comment]
> 当在web端调用Native未定义的方法时，由于使用throw new Error()，导致鸿蒙应用直接退出。 建议改成相同的体验，使用Prompt.showToast方法支持报错信息提示。
> 
> <img alt="image" width="1038" src="https://private-user-images.githubusercontent.com/18252626/321143650-533b9a4f-7025-4da9-8af9-62c39af83520.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDEyMzcsIm5iZiI6MTcxMjc0MDkzNywicGF0aCI6Ii8xODI1MjYyNi8zMjExNDM2NTAtNTMzYjlhNGYtNzAyNS00ZGE5LThhZjktNjJjMzlhZjgzNTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA5MjIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYTYyNTkzZGUzN2Q0YTE2ZGZhMjE3YTE1ZjFhNmNiNDNhMmU4OTc0NjU2ZDk2NzBmMjhmYjVmZGJjYWY4NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yHWKHK_l7YAIllhcj-tIOb4QRMkeotCrkEQqVRi8us4">

👌🏻下个版本优化

**Comment by 751496032** [comment]
> 当在web端调用Native未定义的方法时，由于使用throw new Error()，导致鸿蒙应用直接退出。 建议改成相同的体验，使用Prompt.showToast方法支持报错信息提示。
> 
> <img alt="image" width="1038" src="https://private-user-images.githubusercontent.com/18252626/321143650-533b9a4f-7025-4da9-8af9-62c39af83520.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDE0MjYsIm5iZiI6MTcxMjc0MTEyNiwicGF0aCI6Ii8xODI1MjYyNi8zMjExNDM2NTAtNTMzYjlhNGYtNzAyNS00ZGE5LThhZjktNjJjMzlhZjgzNTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA5MjUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YTZlYjM5NjRiZTgyN2M2ZTA2MTZmZDc1MWRlMDFjMWFhMGE3NjhhNDNkYWRlZjNiYmZjNGIxMTI3OTcwMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EqJudvFZWZq-QwyvoSDsVJbQGnxwt9zV-4gPF42B3jM">

👌🏻下个版本优化，有建议和问题可以多多反馈哈
