### ISSUE TITLE
call调用，希望能添加参数类型检测

### ISSUE THREAD

**Issue by lvcq** [751496032/DSBridge-HarmonyOS#7]
比如 methodName 参数为 undefined， 会导致应用闪退。由于这个是h5页面调用的，无法保证传入参数一定正确，在处理参数前需要做一些必要的检测，减少h5页面对应用的影响。

**Comment by 751496032** [comment]
> 比如 methodName 参数为 undefined， 会导致应用闪退。由于这个是h5页面调用的，无法保证传入参数一定正确，在处理参数前需要做一些必要的检测，减少h5页面对应用的影响。

收到，安排周末发布一个版本
