### ISSUE TITLE
h5调用history.back()无效

### ISSUE THREAD

**Issue by longxianren** [751496032/DSBridge-HarmonyOS#8]
试了下原生的harmonyOS的 web组件是可以触发的

**Comment by 751496032** [comment]
> 试了下原生的harmonyOS的 web组件是可以触发的

ok  晚上看看

**Comment by longxianren** [comment]
问题出在.javaScriptProxy(this.controllerProxy.getJavaScriptProxy())这里。

**Comment by longxianren** [comment]
getJavaScriptProxy(): RealJavaScriptProxy {
    let javaScriptProxy: RealJavaScriptProxy = {
      object: this.bridge.javaScriptProxy().object,
      name: this.bridge.javaScriptProxy().name,
      methodList: this.bridge.javaScriptProxy().methodList,
      controller: this.controller
    }
    return javaScriptProxy
  }。这里的controller传的this.controller，然后就不行。我在使用 web的时候改成：        .javaScriptProxy({
          object: this.controllerProxy.getBridge().javaScriptProxy().object,
          name: this.controllerProxy.getBridge().javaScriptProxy().name,
          methodList: this.controllerProxy.getBridge().javaScriptProxy().methodList,
          controller: this.controllerProxy.getWebViewController()
        })这样就可以正常运行

**Comment by 751496032** [comment]
> 或者改下这个： getJavaScriptProxy(controller: webview.WebviewController): RealJavaScriptProxy { let javaScriptProxy: RealJavaScriptProxy = { object: this.bridge.javaScriptProxy().object, name: this.bridge.javaScriptProxy().name, methodList: this.bridge.javaScriptProxy().methodList, controller: controller } return javaScriptProxy }。把实例化的 controller作为参数传进来。

谢谢反馈
